[walk3r]
root_path = "/home/jay/ag1/padma"
output_dir = "./reports/"
formats = ["json", "csv", "dot"]

# Long walk mode configuration
enable_complexity = true
enable_db_detection = true
enable_db_compliance = true  # NEW!
enable_doc_coverage = true
enable_metrics = true
enable_summary = true

# Database detection customization
db_methods = ["execute", "query", "find", "insert", "update", "delete", "save", "create"]
db_modules = ["sqlite3", "sqlalchemy", "pymongo", "psycopg2", "mysql", "redis", "django.db"]

# Complexity analysis thresholds  
max_function_length = 30
max_complexity_score = 10
max_parameter_count = 6

# Database compliance patterns (customize for your project)
[walk3r.violation_patterns]
direct_redis = [
    "\\.redis\\.",
    "redis\\..*\\(",
    "\\.lpush\\(",
    "\\.xread\\(",
    "\\.hget\\(",
    "\\.zrangebyscore\\(",
    "\\.pipeline\\(\\)",
]
direct_neo4j = [
    "session\\.run\\(",
    "\\.neo4j\\.",
    "driver\\.session\\(",
    "neo4j\\..*\\(",
]
direct_sql = [
    "cursor\\.execute\\(",
    "\\.execute\\s*\\(",
    "SELECT\\s+.*FROM",
    "INSERT\\s+INTO",
    "UPDATE\\s+.*SET",
    "DELETE\\s+FROM",
]

[walk3r.service_patterns]
system_db_service = [
    "system_db\\.store_config\\(",
    "system_db\\.get_config\\(",
    "system_db\\.query_metrics\\(",
    "system_db_service\\.",
]
memory_db_service = [
    "memory_db\\.store_memory\\(",
    "memory_db\\.fetch_memories\\(",
    "memory_db_service\\.",
]
repository_pattern = [
    "Repository\\(",
    "\\.repository\\.",
    "_repo\\.",
]
